### ISSUE TITLE
Not Compiling on Mac 10.12.6 

### ISSUE THREAD

**Issue by siva1024** [marcelstoer/nodemcu-pyflasher#23]
I downloaded and installed both wxPython and esptool.py by I am getting this error message

Traceback (most recent call last):
  File "/Users/.../nodemcu-pyflasher-master/nodemcu-pyflasher.py", line 3, in <module>
    import Main
  File "/Users/.../nodemcu-pyflasher-master/Main.py", line 347, in <module>
    class MySplashScreen(wx.SplashScreen):
AttributeError: 'module' object has no attribute 'SplashScreen'

**Comment by marcelstoer** [comment]
It looks like the wrong wxPython version to me. See https://github.com/marcelstoer/nodemcu-pyflasher/issues/1#issuecomment-272253609
