### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'baudrate'

### ISSUE THREAD

**Issue by clabnet** [marcelstoer/nodemcu-pyflasher#36]
Hi, using version 3.0 I have this error.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\NodeMCU\nodemcu-pyflasher\Main.py", line 76, in run
    esp = ESPLoader.detect_chip(self._config.port, initial_baud)
  File "C:\NodeMCU\nodemcu-pyflasher\esptool.py", line 216, in detect_chip
    detect_port = ESPLoader(port, baud, trace_enabled=trace_enabled)
  File "C:\NodeMCU\nodemcu-pyflasher\esptool.py", line 195, in __init__
    self._set_port_baudrate(baud)
  File "C:\NodeMCU\nodemcu-pyflasher\esptool.py", line 200, in _set_port_baudrate
    self._port.baudrate = baud
AttributeError: 'unicode' object has no attribute 'baudrate'
```
Any suggestion please ? 
Thanks

**Comment by marcelstoer** [comment]
I guess you're not running the binary for Windows but run the Python file directly? Then you need to consider the dependencies as per https://github.com/marcelstoer/nodemcu-pyflasher#build-it-yourself
