### ISSUE TITLE
I can't get pyflasher to work on ubuntu-20.02 (solved )

### ISSUE THREAD

**Issue by Kmiz07** [marcelstoer/nodemcu-pyflasher#82]
I have updated my linux, and after the update, when trying to run pyflasher I get the following error: 

Traceback (most recent call last):
  File "/home/manolo/.local/lib/python3.8/site-packages/wx/core.py", line 2326, in Notify
    self.notify()
  File "/home/manolo/.local/lib/python3.8/site-packages/wx/core.py", line 3532, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/home/manolo/Documentos/guardados/nodemcu-pyflasher-master/Main.py", line 407, in _show_main
    frame = NodeMcuFlasher(None, "NodeMCU PyFlasher")
  File "/home/manolo/Documentos/guardados/nodemcu-pyflasher-master/Main.py", line 157, in __init__
    self._init_ui()
  File "/home/manolo/Documentos/guardados/nodemcu-pyflasher-master/Main.py", line 222, in _init_ui
    serial_boxsizer.Add(reload_button, 0, wx.ALIGN_RIGHT, 20)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /home/wxpy/wxPython-4.1.1/ext/wxWidgets/src/common/sizer.cpp(2168) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers

Could you help me solve the problem?
In principle, I have all the software version requirements fulfilled ...

**Comment by Kmiz07** [comment]
Excuse me. It was as simple as updating the pyflasher version as well.
